# Generated by Django 6.0.7 on 2026-08-03 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('emoji', models.CharField(blank=True, max_length=8)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GeocodeThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_called_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'geocode throttle',
                'verbose_name_plural': 'geocode throttle',
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField(blank=True)),
                ('is_commercial', models.BooleanField(default=False, help_text='Sells a product or service. Shown as a label and filterable; not grounds for rejection on its own.')),
                ('max_active_series', models.PositiveSmallIntegerField(default=5, help_text='How many recurring listings this organizer may run at once. Stops any single submitter from dominating the Programs section.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, help_text="The account that may edit this organizer's listings.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geocode_status', models.CharField(choices=[('pending', 'Not yet geocoded'), ('ok', 'Geocoded'), ('failed', 'Geocoding failed'), ('out_of_region', 'Outside the region'), ('manual', 'Set by hand')], default='pending', max_length=20)),
                ('geocode_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('geocode_error', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['geocode_status'], name='events_venu_geocode_e9b95d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True)),
                ('summary', models.CharField(blank=True, help_text='One line, shown on cards.', max_length=300)),
                ('description', models.TextField(blank=True)),
                ('is_online', models.BooleanField(default=False)),
                ('online_url', models.URLField(blank=True)),
                ('source_url', models.URLField(blank=True, help_text='Where this listing came from.')),
                ('ticket_url', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('is_free', models.BooleanField(default=False)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_note', models.CharField(blank=True, max_length=120)),
                ('age_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_family_friendly', models.BooleanField(default=False)),
                ('accessibility_notes', models.TextField(blank=True)),
                ('listing_type', models.CharField(choices=[('one_off', 'One-off event'), ('series', 'Recurring series')], default='one_off', max_length=10)),
                ('prominence', models.IntegerField(choices=[(1, 'Background — regular program'), (2, 'Listed — appears in the main feed'), (3, 'Featured — highlighted')], default=2, help_text="Where this sits in the feed. A moderator's call.")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Awaiting review'), ('published', 'Published'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=12)),
                ('source', models.CharField(choices=[('submission', 'Submitted'), ('import', 'Imported from a feed'), ('manual', 'Added by a moderator')], default='submission', max_length=12)),
                ('is_commercial', models.BooleanField(default=False)),
                ('series_ends_on', models.DateField(blank=True, null=True)),
                ('renewal_token', models.CharField(blank=True, db_index=True, max_length=64)),
                ('last_renewal_email_at', models.DateTimeField(blank=True, null=True)),
                ('interest_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='events', to='events.category')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_events', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.organizer')),
                ('venue', models.ForeignKey(blank=True, help_text='Leave empty for online-only events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.venue')),
            ],
            options={
                'ordering': ['-prominence', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(blank=True, help_text='Hash of a per-visitor cookie id and IP, for anonymous marks.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='events.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('event', 'user'), name='unique_interest_per_user'), models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('event', 'fingerprint'), name='unique_interest_per_fingerprint')],
            },
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, help_text="Anything specific to this date, e.g. 'Guest speaker'.", max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='events.event')),
            ],
            options={
                'ordering': ['start'],
                'indexes': [models.Index(fields=['start'], name='events_occu_start_9676b5_idx'), models.Index(fields=['event', 'start'], name='events_occu_event_i_a510f2_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'start'), name='unique_event_start')],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'prominence'], name='events_even_status_9bab87_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['listing_type', 'status'], name='events_even_listing_284be3_idx'),
        ),
    ]
