# Generated by Django 6.0.7 on 2026-08-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_drop_online_events'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['end'], name='events_occu_end_45ebcb_idx'),
        ),
        migrations.AddConstraint(
            model_name='occurrence',
            constraint=models.CheckConstraint(condition=models.Q(('end__isnull', True), ('end__gt', models.F('start')), _connector='OR'), name='occurrence_ends_after_it_starts'),
        ),
    ]
