# Generated by Django 6.0.7 on 2026-08-04 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_occurrence_events_occu_end_45ebcb_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRefresh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('reading', 'Reading the page'), ('ready', 'Ready to review'), ('failed', "Couldn't read the page"), ('applied', 'Applied'), ('discarded', 'Discarded')], default='queued', max_length=12)),
                ('draft', models.JSONField(blank=True, default=dict)),
                ('method', models.CharField(blank=True, max_length=12)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('applied_fields', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_refreshes', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refreshes', to='events.event')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_refreshes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'event refreshes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='events_even_status_7fa719_idx')],
            },
        ),
    ]
