# Generated by Django 6.0.7 on 2026-08-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='When off, submissions skip AI enrichment and go straight to the submitter for manual completion.')),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic'), ('openrouter', 'OpenRouter')], default='anthropic', max_length=20)),
                ('base_url', models.URLField(blank=True, default='https://openrouter.ai/api/v1', help_text='OpenRouter only. Ignored by the Anthropic provider.')),
                ('api_key', models.CharField(blank=True, help_text='Leave blank to fall back to the ANTHROPIC_API_KEY / OPENROUTER_API_KEY environment variable.', max_length=255)),
                ('model', models.CharField(default='claude-opus-5', help_text="Anthropic model id, or an OpenRouter model slug such as 'anthropic/claude-haiku-4.5' or 'google/gemini-2.0-flash-001'.", max_length=100)),
                ('max_tokens', models.PositiveIntegerField(default=4096)),
                ('daily_spend_cap_usd', models.DecimalField(decimal_places=2, default=5, help_text='Enrichment stops for the day once estimated spend exceeds this. 0 disables the cap.', max_digits=8)),
            ],
            options={
                'verbose_name': 'AI configuration',
                'verbose_name_plural': 'AI configuration',
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.TextField(blank=True, help_text='Shown on the About page. Markdown-flavoured plain text.')),
                ('submission_guidelines', models.TextField(blank=True, help_text="Shown above the submission form. What belongs here, what doesn't.")),
                ('code_of_conduct', models.TextField(blank=True)),
                ('footer_links', models.JSONField(blank=True, default=list, help_text='List of {"label": ..., "url": ...} objects.')),
            ],
            options={
                'verbose_name': 'site configuration',
                'verbose_name_plural': 'site configuration',
            },
        ),
    ]
