# Generated by Django 6.0.7 on 2026-08-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='effort',
            field=models.CharField(choices=[('low', 'Low — cheapest, fine for tidy pages'), ('medium', 'Medium — a sensible default for extraction'), ('high', 'High')], default='medium', help_text='Anthropic only. Extraction is not a deep-reasoning task, so the lower settings usually hold up well — worth testing before paying for more.', max_length=10),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='input_cost_per_mtok',
            field=models.DecimalField(decimal_places=2, default=3, help_text='USD per million input tokens, for cost estimates.', max_digits=8),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='output_cost_per_mtok',
            field=models.DecimalField(decimal_places=2, default=15, help_text='USD per million output tokens, for cost estimates.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='max_tokens',
            field=models.PositiveIntegerField(default=8192, help_text='Caps thinking and reply together on models that think, so leave headroom above the size of the JSON you expect back.'),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='model',
            field=models.CharField(default='claude-opus-5', help_text="Anthropic model id, or an OpenRouter model slug such as 'anthropic/claude-sonnet-5' or 'google/gemini-2.0-flash-001'.", max_length=100),
        ),
    ]
