# Generated by Django 6.0.7 on 2026-08-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aiconfig_effort_aiconfig_input_cost_per_mtok_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiconfig',
            name='effort',
        ),
        migrations.RemoveField(
            model_name='aiconfig',
            name='provider',
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='api_key',
            field=models.CharField(blank=True, help_text='Leave blank to fall back to the OPENROUTER_API_KEY environment variable.', max_length=255),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='base_url',
            field=models.URLField(blank=True, default='https://openrouter.ai/api/v1', help_text='Any OpenAI-compatible endpoint. Leave as-is for OpenRouter.'),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='model',
            field=models.CharField(default='anthropic/claude-sonnet-5', help_text="A model slug the endpoint understands, e.g. 'anthropic/claude-sonnet-5' or 'google/gemini-2.0-flash-001'.", max_length=100),
        ),
    ]
