# Generated by Django 6.0.7 on 2026-08-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_aiconfig_effort_remove_aiconfig_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='head_html',
            field=models.TextField(blank=True, help_text='Injected verbatim into &lt;head&gt; on every page: a search-console verification tag, an analytics snippet. Not escaped and not checked — whatever is pasted here runs on every page, for every visitor. Superusers only.', verbose_name='extra <head> HTML'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='script_hosts',
            field=models.TextField(blank=True, help_text='One origin per line, e.g. https://plausible.io. Anything the HTML above loads a script from, or sends data to, has to be listed here or the Content-Security-Policy blocks it — and a blocked snippet looks exactly like one that was never pasted.', verbose_name='script hosts to allow'),
        ),
    ]
