# Generated by Django 6.0.7 on 2026-08-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_siteconfig_head_html_siteconfig_script_hosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='json_schema_probed_model',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='json_schema_supported',
            field=models.BooleanField(editable=False, null=True),
        ),
    ]
