# Generated by Django 6.0.7 on 2026-08-13 01:39

import core.themes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_aiconfig_json_schema_probed_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='theme',
            field=models.CharField(choices=core.themes.theme_choices, default='classic', help_text='How the public pages look. Changing this restyles the site for every visitor immediately; it does not touch any listing.', max_length=32),
        ),
    ]
