# Generated by Django 6.0.7 on 2026-08-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='source_advice',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
