# Generated by Django 6.0.7 on 2026-09-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submission_source_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='pasted_text',
            field=models.TextField(blank=True),
        ),
    ]
