# Generated by Django 6.0.7 on 2026-09-29 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_apitoken'),
        ('submissions', '0003_submission_pasted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='api_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='accounts.apitoken'),
        ),
    ]
