# Generated by Django 6.0.7 on 2026-08-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrichmentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(blank=True)),
                ('method', models.CharField(choices=[('structured', "Page's own event data"), ('llm', 'Language model')], max_length=12)),
                ('status', models.CharField(choices=[('ok', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=10)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
