# Generated by Django 6.0.7 on 2026-08-03 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrichment', '0001_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrichmentrun',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrichment_runs', to='submissions.submission'),
        ),
        migrations.AddIndex(
            model_name='enrichmentrun',
            index=models.Index(fields=['created_at', 'status'], name='enrichment__created_f5be4a_idx'),
        ),
    ]
