# Generated by Django 6.0.7 on 2026-08-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrichment', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrichmentrun',
            name='provider',
        ),
        migrations.AddField(
            model_name='enrichmentrun',
            name='endpoint',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
