# Generated by Django 6.0.7 on 2026-08-04 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrichment', '0003_remove_enrichmentrun_provider_enrichmentrun_endpoint'),
        ('events', '0005_eventrefresh'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrichmentrun',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrichment_runs', to='events.event'),
        ),
    ]
