# Generated by Django 6.0.7 on 2026-08-06 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='What this is, for finding it again later.', max_length=200)),
                ('alt_text', models.CharField(blank=True, help_text='What the image shows, for readers using a screen reader. Leave blank only if it is purely decorative.', max_length=300)),
                ('data', models.BinaryField()),
                ('thumbnail', models.BinaryField()),
                ('content_type', models.CharField(editable=False, max_length=40)),
                ('width', models.PositiveIntegerField(editable=False)),
                ('height', models.PositiveIntegerField(editable=False)),
                ('byte_size', models.PositiveIntegerField(editable=False)),
                ('checksum', models.CharField(db_index=True, editable=False, max_length=64)),
                ('original_filename', models.CharField(blank=True, editable=False, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="The page's web address. Changing it breaks existing links.", max_length=200, unique=True)),
                ('body', models.TextField(blank=True, help_text='Markdown. Use the media library to add images.')),
                ('body_html', models.TextField(blank=True, editable=False)),
                ('is_published', models.BooleanField(default=False, help_text='Unpublished pages are visible to moderators at their address, nobody else.', verbose_name='published')),
                ('show_in_footer', models.BooleanField(default=True, help_text='List this page in the site footer.', verbose_name='show in the footer')),
                ('footer_order', models.SmallIntegerField(default=0, help_text='Lower numbers sort first.', verbose_name='footer position')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['footer_order', 'title'],
            },
        ),
    ]
